name: mip_figures
channels:
  - conda-forge
  # - defaults
dependencies:
  - python=3.10 # Remove for tox.ini & setup.py
  - pip
  - altair
  # - altair_saver
  - pandas
  # - selenium
  # - ipykernel
  # - jupyter
  # - python-chromedriver-binary
  - vl-convert-python