name: Run Jupyter Notebook

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  run_notebook:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"  # Choose the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter altair altair_saver pandas selenium

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Discover Notebooks
        run: |
          notebooks=$(find . -name "*.ipynb")
          echo "$notebooks"
        id: discover_notebooks

      - name: Run Notebooks
        run: |
          for notebook in ${{ steps.discover_notebooks.outputs.notebooks }}; do
            notebook_dir=$(dirname "$notebook")
            cd "$notebook_dir"
            jupyter nbconvert --to notebook --execute "$(basename "$notebook")"
            cd -
          done

      - name: Commit figures
        run: |
          if git diff-index --quiet HEAD^ HEAD -- './*.png'; then
            echo "No changes in the figures."
            exit 0
          else
            echo "Committing all changes detected in the figures."
            git add ./*.png
            git commit -m "Update saved figures"
          fi
      
      - name: Commit changes to notebooks
        run: |
          if git diff-index --quiet HEAD^ HEAD -- './*.ipynb'; then
            echo "No changes in the notebooks."
            exit 0
          else
            echo "Committing all changes detected in the notebooks."
            git add ./*.ipynb
            git commit -m "Update figures in notebooks"
          fi

      - name: Push changes to repository
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
